name: Build and Test Factorizer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t factorizer-bot .

    - name: Run the bot
      run: docker run -e DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} factorizer-bot
